version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  app:
    build: .
    volumes:
      - .:/Ryoken
      - public-data:/Ryoken/public
      - tmp-data:/Ryoken/tmp
      - log-data:/Ryoken/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" 

  
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

