version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/ryoken
      - public-data:/ryoken/public
      - tmp-data:/ryoken/tmp
      - log-data:/ryoken/log
    depends_on:
      - db
    environment:
      RAILS_ENV: production
    command: bundle exec puma -C config/puma.rb

  app:
    build:
      context: containers/nginx
      dockerfile: Dockerfile
    volumes:
      - public-data:/ryoken/public
      - tmp-data:/ryoken/tmp
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

